site_name: 三分热度

# Contents
nav:
  - Home: index.md
  - 机器学习:
    - A guide for academic researchers: ml/A_guide_for_academic_researchers.md
  - 知识图谱:
    - 【知识建模】领域知识图谱构建: kg/领域知识图谱构建.md
    - 【知识建模】Protege: kg/Protege.md
    - 【知识存储】图数据库比较: kg/graphdb.md
    - 【知识推理】规则语言和规则引擎: kg/规则语言和规则引擎.md
    - 【RDF】RDF Mapping: kg/RDFMapping.md
    - 【RDF】D2RQ: kg/D2RQ.md
    - 【RDF】RDF映射工具Ontop: kg/ontop.md
    - 【Jena】Apache Jena与Fuseki: kg/Jena_and_Fuseki.md
    - 【Jena】Fuseki推理实践: kg/Fuseki推理实践.md
    - 【Jena】Jena推理实践: kg/Jena推理实践.md
    - 【Jena】Jena全文检索: kg/Jena全文检索.md
  - code:
    - 【git】合并两个代码仓的commit记录: code/git合并两个代码仓.md

# Extensions
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
      linenums: true
  - def_list
  - footnotes
  - meta
  - toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.snippets
  - pymdownx.progressbar
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: math
          class: arithmatex
          format: !!python/name:pymdownx.arithmatex.fence_mathjax_format
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde